/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.ChiTietGioHangBUS;
import BUS.HoaDonBUS;
import BUS.NhanVienBUS;
import DTO.ChiTietGioHang;
import DTO.HoaDon;

/**
 *
 * @author admin
 */
public class ChiTietHoaDonUI extends javax.swing.JDialog {

    /**
     * Creates new form ChiTietHoaDonUI
     */
    private int mahoadon;
    
    public ChiTietHoaDonUI(java.awt.Frame parent, boolean modal, int mahoadon) {
        super(parent, modal);
        this.mahoadon = mahoadon;
        initComponents();
        this.setLocationRelativeTo(null);
        showChiTiet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMonAn = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();
        txtMaGioHang = new javax.swing.JTextField();
        txtThuNgan = new javax.swing.JTextField();
        txtNVGoimon = new javax.swing.JTextField();
        txtMaBan = new javax.swing.JTextField();
        txtNgayLap = new javax.swing.JTextField();
        txtTongTien = new javax.swing.JTextField();
        txtNVThanhtoan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Chi tiết hoá đơn.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel1.setText("Mã hoá đơn");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel4.setText("Thu ngân");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel5.setText("Nhân viên gọi món");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel6.setText("Nhân viên thanh toán");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        txtMonAn.setEditable(false);
        txtMonAn.setColumns(20);
        txtMonAn.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        txtMonAn.setRows(5);
        jScrollPane1.setViewportView(txtMonAn);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 260, 90));

        jLabel7.setText("Mã bàn");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel8.setText("Ngày lập");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        jLabel9.setText("Tổng tiền");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        jLabel10.setText("Mã giỏ hàng");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        txtMaHoaDon.setEditable(false);
        txtMaHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        txtMaHoaDon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.add(txtMaHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 120, -1));

        txtMaGioHang.setEditable(false);
        txtMaGioHang.setBackground(new java.awt.Color(255, 255, 255));
        txtMaGioHang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtMaGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaGioHangActionPerformed(evt);
            }
        });
        jPanel1.add(txtMaGioHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 120, -1));

        txtThuNgan.setEditable(false);
        txtThuNgan.setBackground(new java.awt.Color(255, 255, 255));
        txtThuNgan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.add(txtThuNgan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 120, -1));

        txtNVGoimon.setEditable(false);
        txtNVGoimon.setBackground(new java.awt.Color(255, 255, 255));
        txtNVGoimon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.add(txtNVGoimon, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 120, -1));

        txtMaBan.setEditable(false);
        txtMaBan.setBackground(new java.awt.Color(255, 255, 255));
        txtMaBan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtMaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaBanActionPerformed(evt);
            }
        });
        jPanel1.add(txtMaBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 120, -1));

        txtNgayLap.setEditable(false);
        txtNgayLap.setBackground(new java.awt.Color(255, 255, 255));
        txtNgayLap.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.add(txtNgayLap, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 150, -1));

        txtTongTien.setEditable(false);
        txtTongTien.setBackground(new java.awt.Color(255, 255, 255));
        txtTongTien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.add(txtTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 150, -1));

        txtNVThanhtoan.setEditable(false);
        txtNVThanhtoan.setBackground(new java.awt.Color(255, 255, 255));
        txtNVThanhtoan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtNVThanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNVThanhtoanActionPerformed(evt);
            }
        });
        jPanel1.add(txtNVThanhtoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 120, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hoadon1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaGioHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaGioHangActionPerformed

    private void txtMaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaBanActionPerformed

    private void txtNVThanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNVThanhtoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNVThanhtoanActionPerformed
    
    private void showChiTiet(){
        HoaDonBUS hdBUS = new HoaDonBUS();
        NhanVienBUS nvBUS = new NhanVienBUS();
        ChiTietGioHangBUS ctghBUS = new ChiTietGioHangBUS();
        HoaDon hd = hdBUS.getHoaDonTheoma(mahoadon);
        
        String nvgoimon = hd.getMaNvYeuCau()+" - "+nvBUS.getTenTheoma(hd.getMaNvYeuCau());
        String nvthanhtoan = hd.getMaNvThanhToan()+" - "+nvBUS.getTenTheoma(hd.getMaNvThanhToan());
        String monan = "        Món đã gọi      \n------------------------\n";
        for (ChiTietGioHang ct: ctghBUS.getlistChiTietGH(hd.getMaGiohang())){
            monan += ct.getTenMon()+"\n";
        }
                
        txtMaHoaDon.setText(mahoadon+"");
        txtMaGioHang.setText(hd.getMaGiohang()+"");
        txtMaBan.setText(hd.getMaBan());
        txtThuNgan.setText(nvBUS.getTenTheoma(hd.getMaNvQuay()));
        txtNVGoimon.setText(nvgoimon);
        txtNVThanhtoan.setText(nvthanhtoan);
        txtNgayLap.setText(hdBUS.formatNgay(hd.getNgayLap()));
        txtTongTien.setText(hdBUS.formatSo(hd.getTongTien())+" VND");
        txtMonAn.setText(monan);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtMaBan;
    private javax.swing.JTextField txtMaGioHang;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextArea txtMonAn;
    private javax.swing.JTextField txtNVGoimon;
    private javax.swing.JTextField txtNVThanhtoan;
    private javax.swing.JTextField txtNgayLap;
    private javax.swing.JTextField txtThuNgan;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
