/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.ChiTietGioHangBUS;
import BUS.DangNhapBUS;
import BUS.GioHangBUS;
import BUS.HoaDonBUS;
import BUS.NhanVienBUS;
import DTO.ChiTietGioHang;
import DTO.HoaDon;
import static GUI.QuanLyTiemPhoUI.maGioHangSelected;
import java.awt.Color;
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;

/**
 *
 * @author admin
 */
public class HoaDonUI extends javax.swing.JDialog {

    /**
     * Creates new form ThanhToan
     */
    Color colorHover = new Color(204, 0, 0);
    Color colorDefault = new Color(0, 66, 67);
    HoaDonBUS hdBUS = new HoaDonBUS();
    
    public String maGioHang = "";
    int tongtien = 0;
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    Date date;

    public HoaDonUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        hienthiHoaDon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHoaDon = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        pnbtnThanhToan = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        txtHoaDon.setEditable(false);
        txtHoaDon.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtHoaDon.setContentType("text/html"); // NOI18N
        txtHoaDon.setText("");
        jScrollPane1.setViewportView(txtHoaDon);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/thanhtoan.png"))); // NOI18N

        pnbtnThanhToan.setBackground(new java.awt.Color(0, 66, 67));
        pnbtnThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnbtnThanhToanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnbtnThanhToanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnbtnThanhToanMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Thanh toán");

        javax.swing.GroupLayout pnbtnThanhToanLayout = new javax.swing.GroupLayout(pnbtnThanhToan);
        pnbtnThanhToan.setLayout(pnbtnThanhToanLayout);
        pnbtnThanhToanLayout.setHorizontalGroup(
            pnbtnThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnbtnThanhToanLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnbtnThanhToanLayout.setVerticalGroup(
            pnbtnThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(pnbtnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnbtnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnbtnThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnbtnThanhToanMouseClicked
        Calendar cal = Calendar.getInstance();
        date = cal.getTime();
        tongtien = 0;
        hienthiHoaDon();
        luuHoaDon();
        updateGiohang();
    }//GEN-LAST:event_pnbtnThanhToanMouseClicked

    private void pnbtnThanhToanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnbtnThanhToanMouseEntered
        pnbtnThanhToan.setBackground(colorHover);
    }//GEN-LAST:event_pnbtnThanhToanMouseEntered

    private void pnbtnThanhToanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnbtnThanhToanMouseExited
        pnbtnThanhToan.setBackground(colorDefault);
    }//GEN-LAST:event_pnbtnThanhToanMouseExited
    
    private void luuHoaDon(){
        int magh = maGioHangSelected;
        Date ngaylap = date;
        int tien = tongtien;
        int manvquay = DangNhapBUS.taikhoanlogin.getMaNhanVien();
        if(hdBUS.updateHoaDon(magh, ngaylap, manvquay, tien)){
            inHoaDon();
//            updateGiohang();
        }
    }
    
    private void updateGiohang() {
        GioHangBUS ghBUS = new GioHangBUS();
        if (ghBUS.updateTinhTrangGioHang(maGioHangSelected)) {
            this.dispose();
        }
    }
    
    private void inHoaDon(){
        try {
            if (!txtHoaDon.getText().equals("")) {
                txtHoaDon.print();

            }
        } catch (PrinterException ex) {
            System.out.println(ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnbtnThanhToan;
    private javax.swing.JEditorPane txtHoaDon;
    // End of variables declaration//GEN-END:variables

    private void hienthiHoaDon() {
        
        ChiTietGioHangBUS ctghBUS = new ChiTietGioHangBUS();
        NhanVienBUS nvBUS = new NhanVienBUS();
        String mahd;
        String maban = "";
        int manvyc = 0;
        int manvtt = 0;
        if (hdBUS.getmaHoaDonTheoMaGH(QuanLyTiemPhoUI.maGioHangSelected) == -1) {
            return;
        } else {
            mahd = hdBUS.getmaHoaDonTheoMaGH(QuanLyTiemPhoUI.maGioHangSelected) + "";
        }

        for (HoaDon hd : hdBUS.getlistHoaDonTheomaGH(maGioHangSelected)) {
//            mahd = hd.getMaHoaDon();
            maban = hd.getMaBan();
            manvyc = hd.getMaNvYeuCau();
            manvtt = hd.getMaNvThanhToan();
        }

        String hoadon = "<html>\n"
                + "<head>\n"
                + "<style>\n"
                + "body {margin-left: 40px;display: flex;justify-content: center;}\n"
                + "th,td {padding: 2px 8px;}\n"
                + "th {border-bottom: 1px solid;}\n"
                + "h5 { margin: 10px 120px;text-align: center;padding: 0 12px;font-size: 20px;border-top: 3px solid;\n"
                + "border-bottom: 1px solid;font-family: sans-serif;font-weight: 600;}\n"
                + "h3 {text-align: center;padding: 0px;}\n"
                + "p {margin-left: 100px;}\n"
                + "ul {list-style: none;}\n"
                + "</style>\n"
                + "</head>\n"
                + "<body>\n"
                + "<div>\n"
                + "<h5>Phở 8</h5>\n"
                + "<h3>HOÁ ĐƠN BÁN HÀNG</h3>\n"
                + "<p>Mã hoá đơn:"
                + mahd
                + "</p>\n"
                + "<table>\n"
                + "    <tr>\n"
                + "        <th>Stt</th>\n"
                + "        <th>Tên món</th>\n"
                + "        <th>Số lượng</th>\n"
                + "        <th>Đơn giá</th>\n"
                + "        <th>Thành tiền</th>\n"
                + "    </tr>\n";

        int stt = 0;
        for (ChiTietGioHang ctgh : ctghBUS.getlistChiTietGH(maGioHangSelected)) {
            hoadon += "    <tr>";
            stt += 1;
            hoadon += "<td>" + stt + "</td>";
            hoadon += "<td>" + ctgh.getTenMon() + "</td>";
            hoadon += "<td>" + ctgh.getSoLuong() + "</td>";
            hoadon += "<td>" + hdBUS.formatSo(ctgh.getDonGia())+ "</td>";
            hoadon += "<td>" + hdBUS.formatSo(ctgh.getThanhTien()) + "</td>";
            tongtien += ctgh.getThanhTien();
            hoadon += "    </tr>";
        }
        String t;
        if(date == null){
            t="";
        }else{
            t = sdf.format(date);
        }
        hoadon += "</table>\n"
                + "<label>Tổng tiền: " +hdBUS.formatSo(tongtien) + " VND</label>\n"
                + "<ul>\n"
                + "<li>Số bàn: " + maban + "</li>\n"
                + "<li>Nhân viên gọi món: " + nvBUS.getTenTheoma(manvyc) + "</li>\n"
                + "<li>Nhân viên thanh toán: " + nvBUS.getTenTheoma(manvtt) + "</li>\n"
                + "<li>Thu ngân:" + DangNhapBUS.taikhoanlogin.getMaNhanVien() + " </li>\n"
                + "<li>Ngày lập: " +t+ "</li>\n"
                + "</ul>\n"
                + "<strong>Cảm ơn quý khách !</strong>\n"
                + "</div>\n"
                + "</body>\n"
                + "</body>\n"
                + "</html>";
        txtHoaDon.setText(hoadon);
    }
}
