/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.ChiTietGioHangBUS;
import BUS.LoaiToBUS;
import BUS.ToppingBUS;
import DTO.LoaiTo;
import DTO.Topping;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class MenuGoiMon extends javax.swing.JDialog {

    /**
     * Creates new form MenuGoiMon
     */
    Color colorHover = new Color(204, 0, 0);
    Color colorDefault = new Color(0, 66, 67);
    private DefaultListModel<Topping> dlmTopping;
    private ToppingBUS tpBUS = new ToppingBUS();
    ArrayList<JCheckBox> listCB;
    int demSoLuongThit = 0;
    int gioiHan = 0;
    boolean checkGoiMon = true; //True la Pho - false la topping
    LoaiTo loaitoSelected;
    ChiTietGioHangBUS ctghBUS = new ChiTietGioHangBUS();

    public MenuGoiMon(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.getRootPane().setOpaque(false);
        this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        this.setBackground(new Color(0, 0, 0, 0));

        hienthiListTopping();
        hienthiCboLoaiTo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgChonMon = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cboLoaiTo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbTai = new javax.swing.JCheckBox();
        cbNam = new javax.swing.JCheckBox();
        cbGau = new javax.swing.JCheckBox();
        cbGaan = new javax.swing.JCheckBox();
        cbBoVien = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtSoLuong_pho = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTopping = new javax.swing.JList<>();
        btnAddGioHang = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtSoLuong_tp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnPho = new javax.swing.JRadioButton();
        btnTopping = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboLoaiTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiToActionPerformed(evt);
            }
        });
        jPanel1.add(cboLoaiTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 164, -1));

        jLabel2.setText("Loại tô");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel3.setText("Loại thịt");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        cbTai.setBackground(new java.awt.Color(255, 255, 255));
        cbTai.setText("Tái");
        cbTai.setName(""); // NOI18N
        cbTai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTaiActionPerformed(evt);
            }
        });
        jPanel1.add(cbTai, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 191, -1, -1));

        cbNam.setBackground(new java.awt.Color(255, 255, 255));
        cbNam.setText("Nạm");
        cbNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNamActionPerformed(evt);
            }
        });
        jPanel1.add(cbNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 191, -1, -1));

        cbGau.setBackground(new java.awt.Color(255, 255, 255));
        cbGau.setText("Gầu");
        cbGau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGauActionPerformed(evt);
            }
        });
        jPanel1.add(cbGau, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 191, -1, -1));

        cbGaan.setBackground(new java.awt.Color(255, 255, 255));
        cbGaan.setText("Gân");
        cbGaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGaanActionPerformed(evt);
            }
        });
        jPanel1.add(cbGaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 232, -1, -1));

        cbBoVien.setBackground(new java.awt.Color(255, 255, 255));
        cbBoVien.setText("Bò viên");
        cbBoVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBoVienActionPerformed(evt);
            }
        });
        jPanel1.add(cbBoVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 232, -1, -1));

        jLabel5.setText("Số lượng");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        txtSoLuong_pho.setText("1");
        txtSoLuong_pho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuong_phoActionPerformed(evt);
            }
        });
        jPanel1.add(txtSoLuong_pho, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 164, -1));

        listTopping.setEnabled(false);
        listTopping.setSelectionBackground(new java.awt.Color(2, 128, 62));
        listTopping.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                listToppingAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(listTopping);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 180, 161));

        btnAddGioHang.setBackground(new java.awt.Color(0, 66, 67));
        btnAddGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddGioHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddGioHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddGioHangMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Thêm vào hoá đơn");

        javax.swing.GroupLayout btnAddGioHangLayout = new javax.swing.GroupLayout(btnAddGioHang);
        btnAddGioHang.setLayout(btnAddGioHangLayout);
        btnAddGioHangLayout.setHorizontalGroup(
            btnAddGioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAddGioHangLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(21, 21, 21))
        );
        btnAddGioHangLayout.setVerticalGroup(
            btnAddGioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(btnAddGioHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, -1, 30));

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_25px_2.png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        jPanel1.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Choose", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N

        txtSoLuong_tp.setText("1");
        txtSoLuong_tp.setEnabled(false);

        jLabel4.setText("Số lượng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtSoLuong_tp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSoLuong_tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 100, 160));

        btnPho.setBackground(new java.awt.Color(255, 255, 255));
        bgChonMon.add(btnPho);
        btnPho.setSelected(true);
        btnPho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhoActionPerformed(evt);
            }
        });
        jPanel1.add(btnPho, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        btnTopping.setBackground(new java.awt.Color(255, 255, 255));
        bgChonMon.add(btnTopping);
        btnTopping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToppingActionPerformed(evt);
            }
        });
        jPanel1.add(btnTopping, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    private void cbGauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGauActionPerformed
        if (cbGau.isSelected()) {
            demSoLuongThit += 1;
        } else {
            demSoLuongThit -= 1;
        }
        kiemtraCheckBox();
    }//GEN-LAST:event_cbGauActionPerformed

    private void txtSoLuong_phoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuong_phoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuong_phoActionPerformed

    private void btnAddGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddGioHangMouseClicked

        if (checkGoiMon) {
            thongBaoQuaGioiHan();
            if (demSoLuongThit == 0) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn thịt !");
                txtSoLuong_pho.setEnabled(true);
                cbBoVien.setEnabled(true);
                cbGaan.setEnabled(true);
                cbGau.setEnabled(true);
                cbNam.setEnabled(true);
                cbTai.setEnabled(true);
                return;
            }
            xulyGoiMon_pho();
        } else {
            xulyGoiMon_topping();
        }

    }//GEN-LAST:event_btnAddGioHangMouseClicked

    private void btnAddGioHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddGioHangMouseEntered
        btnAddGioHang.setBackground(colorHover);
    }//GEN-LAST:event_btnAddGioHangMouseEntered

    private void btnAddGioHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddGioHangMouseExited
        btnAddGioHang.setBackground(colorDefault);
    }//GEN-LAST:event_btnAddGioHangMouseExited

    private void btnPhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhoActionPerformed
        checkGoiMon = true;
        listTopping.setEnabled(false);
        txtSoLuong_tp.setEnabled(false);

        cboLoaiTo.setEnabled(true);
        txtSoLuong_pho.setEnabled(true);
        cbBoVien.setEnabled(true);
        cbGaan.setEnabled(true);
        cbGau.setEnabled(true);
        cbNam.setEnabled(true);
        cbTai.setEnabled(true);
    }//GEN-LAST:event_btnPhoActionPerformed

    private void btnToppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToppingActionPerformed
        checkGoiMon = false;
        listTopping.setEnabled(true);
        txtSoLuong_tp.setEnabled(true);

        cboLoaiTo.setEnabled(false);
        txtSoLuong_pho.setEnabled(false);
        cbBoVien.setEnabled(false);
        cbGaan.setEnabled(false);
        cbGau.setEnabled(false);
        cbNam.setEnabled(false);
        cbTai.setEnabled(false);
    }//GEN-LAST:event_btnToppingActionPerformed

    private void cbTaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTaiActionPerformed
        if (cbTai.isSelected()) {
            demSoLuongThit += 1;
        } else {
            demSoLuongThit -= 1;
        }
        kiemtraCheckBox();
    }//GEN-LAST:event_cbTaiActionPerformed

    private void cbNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNamActionPerformed
        if (cbNam.isSelected()) {
            demSoLuongThit += 1;
        } else {
            demSoLuongThit -= 1;
        }
        kiemtraCheckBox();
    }//GEN-LAST:event_cbNamActionPerformed

    private void cbGaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGaanActionPerformed
        if (cbGaan.isSelected()) {
            demSoLuongThit += 1;
        } else {
            demSoLuongThit -= 1;
        }
        kiemtraCheckBox();
    }//GEN-LAST:event_cbGaanActionPerformed

    private void cbBoVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBoVienActionPerformed
        if (cbBoVien.isSelected()) {
            demSoLuongThit += 1;
        } else {
            demSoLuongThit -= 1;
        }
        kiemtraCheckBox();
    }//GEN-LAST:event_cbBoVienActionPerformed

    private void cboLoaiToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiToActionPerformed
        if (cboLoaiTo.getSelectedIndex() == -1) {
            return;
        }
        cbBoVien.setEnabled(true);
        cbGaan.setEnabled(true);
        cbGau.setEnabled(true);
        cbNam.setEnabled(true);
        cbTai.setEnabled(true);
        
        cbBoVien.setSelected(false);
        cbGaan.setSelected(false);
        cbGau.setSelected(false);
        cbNam.setSelected(false);
        cbTai.setSelected(false);
        demSoLuongThit = 0;
        
        loaitoSelected = (LoaiTo) cboLoaiTo.getSelectedItem();
        xulyGioHan();

    }//GEN-LAST:event_cboLoaiToActionPerformed

    private void listToppingAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_listToppingAncestorAdded

    }//GEN-LAST:event_listToppingAncestorAdded

    public void xulyGioHan() {
        if (cboLoaiTo.getSelectedIndex() == 1) {
            gioiHan = 2;
        } else if (cboLoaiTo.getSelectedIndex() == 2) {
            gioiHan = 3;
        } else if (cboLoaiTo.getSelectedIndex() == 3) {
            gioiHan = 4;
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgChonMon;
    private javax.swing.JPanel btnAddGioHang;
    private javax.swing.JRadioButton btnPho;
    private javax.swing.JRadioButton btnTopping;
    private javax.swing.JCheckBox cbBoVien;
    private javax.swing.JCheckBox cbGaan;
    private javax.swing.JCheckBox cbGau;
    private javax.swing.JCheckBox cbNam;
    private javax.swing.JCheckBox cbTai;
    private javax.swing.JComboBox<LoaiTo> cboLoaiTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblExit;
    private javax.swing.JList<Topping> listTopping;
    private javax.swing.JTextField txtSoLuong_pho;
    private javax.swing.JTextField txtSoLuong_tp;
    // End of variables declaration//GEN-END:variables

    private void hienthiListTopping() {
        dlmTopping = new DefaultListModel<>();
        for (Topping tp : tpBUS.getlistLoaiTopping()) {
            dlmTopping.addElement(tp);
        }
        listTopping.setModel(dlmTopping);
    }

    private void hienthiCboLoaiTo() {
        LoaiToBUS ltBUS = new LoaiToBUS();
        cboLoaiTo.addItem(null);
        for (LoaiTo lt : ltBUS.getlistLoaiTo()) {
            cboLoaiTo.addItem(lt);
        }
    }

    private void kiemtraCheckBox() {
        listCB = new ArrayList<>();
        listCB.add(cbGau);
        listCB.add(cbBoVien);
        listCB.add(cbGaan);
        listCB.add(cbTai);
        listCB.add(cbNam);

        for (JCheckBox cb : listCB) {
            if (demSoLuongThit >= gioiHan) {
                if (!cb.isSelected()) {
                    cb.setEnabled(false);
                }
            } else {

                cb.setEnabled(true);
            }
        }
    }

    private void thongBaoQuaGioiHan() {
        if (demSoLuongThit > gioiHan) {
            JOptionPane.showMessageDialog(null, "Thịt vượt quá giới hạn !\n"
                    + "Giới hạn " + cboLoaiTo.getSelectedItem() + " :" + gioiHan, "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void xulyGoiMon_pho() {
        if (cboLoaiTo.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Chưa chọn loại to!");
            return;
        } else if (cboLoaiTo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Loại tô không được để trống");
            return;
        }
        int magh = QuanLyTiemPhoUI.maGioHangSelected;
        int maloaito = loaitoSelected.getMaLoaiTo();
        String loaithit = "";
        for (JCheckBox cb : listCB) {
            if (cb.isSelected()) {
                loaithit += cb.getActionCommand() + " - ";
            }
        }
        String soluong = txtSoLuong_pho.getText();

        if (ctghBUS.themPho(magh, checkGoiMon, maloaito, loaithit, soluong)) {
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Gọi món thất bại");
        }

    }

    private void xulyGoiMon_topping() {
        if (listTopping.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Chưa chọn Topping !");
            return;
        }
        int magh = QuanLyTiemPhoUI.maGioHangSelected;
        Topping tp = listTopping.getSelectedValue();
        int matp = tp.getMaTopping();
        String tentp = tp.getTenTopping();
        String soluong = txtSoLuong_tp.getText();
        if (ctghBUS.themTopping(magh, checkGoiMon, matp, tentp, soluong)) {
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Gọi món thất bại");
        }
    }

}
