/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.ChucVuBUS;
import BUS.NhanVienBUS;
import BUS.TaiKhoanBUS;
import DTO.ChucVu;
import DTO.NhanVien;
import DTO.TaiKhoan;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class QuanLyNhanVienUI extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyNhanVienUI
     */
    Color colorButtonHover = new Color(24, 101, 109);
    Color colorButtonDefault = new Color(0, 66, 67);
    Color colorEnable = new Color(153, 153, 153);
    private DefaultTableModel dtmNhanvien;
    private DefaultTableModel dtmTaikhoan;
    private NhanVienBUS nvBUS = new NhanVienBUS();
    private TaiKhoanBUS tkBUS = new TaiKhoanBUS();
    ChucVu chucvuSelected = null;
    boolean gioitinhSelected;
    boolean checkUpdate;

    public QuanLyNhanVienUI() {
        initComponents();
        Color headerTable = new Color(205, 39, 49);
        tblNhanVien.getTableHeader().setOpaque(false);
        tblNhanVien.getTableHeader().setBackground(headerTable);
        tblNhanVien.getTableHeader().setForeground(Color.white);

        tblTaikhoan.getTableHeader().setOpaque(false);
        tblTaikhoan.getTableHeader().setBackground(headerTable);
        tblTaikhoan.getTableHeader().setForeground(Color.white);

        pnThemNhanvien.setVisible(false);
        pnTaoTaikhoan.setVisible(false);
        hienthiNhanvien();
        hienthiTaiKhoan();
        hienthiChucvu();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGioiTinh = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        pnButtonSuaNV = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        pnButtonThemNV = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        pnButtonXoaNV = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        pnThemNhanvien = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        btnNam = new javax.swing.JRadioButton();
        btnNu = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        pnButtonLuuNV = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        pnButtonTaoTK = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        cboChucVu = new javax.swing.JComboBox<>();
        txtSDT = new javax.swing.JTextField();
        pnTaoTaikhoan = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMaTK_add = new javax.swing.JTextField();
        txtTaiKhoan_add = new javax.swing.JTextField();
        txtMatKhau_add = new javax.swing.JTextField();
        pnButtonLuuTK = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTaikhoan = new javax.swing.JTable();
        pnButtonXoaTK = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        pnButtonSuaTK = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        pncardleft = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtTenTK_up = new javax.swing.JTextField();
        txtMatKhau_up = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtMaTK_up = new javax.swing.JTextField();
        pnButtonUpdateTK = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jTabbedPane1.setBackground(new java.awt.Color(0, 66, 67));
        jTabbedPane1.setOpaque(true);

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên NV", "Giới tính", "Địa chỉ", "SĐT", "Chức vụ"
            }
        ));
        tblNhanVien.setRowHeight(20);
        tblNhanVien.setSelectionBackground(new java.awt.Color(2, 128, 62));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);
        if (tblNhanVien.getColumnModel().getColumnCount() > 0) {
            tblNhanVien.getColumnModel().getColumn(0).setMaxWidth(100);
            tblNhanVien.getColumnModel().getColumn(2).setMaxWidth(100);
            tblNhanVien.getColumnModel().getColumn(5).setMaxWidth(150);
        }

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        pnButtonSuaNV.setBackground(new java.awt.Color(153, 153, 153));
        pnButtonSuaNV.setEnabled(false);
        pnButtonSuaNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnButtonSuaNVMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnButtonSuaNVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnButtonSuaNVMouseExited(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_edit_property_18px.png"))); // NOI18N
        jLabel17.setText("Sửa");

        javax.swing.GroupLayout pnButtonSuaNVLayout = new javax.swing.GroupLayout(pnButtonSuaNV);
        pnButtonSuaNV.setLayout(pnButtonSuaNVLayout);
        pnButtonSuaNVLayout.setHorizontalGroup(
            pnButtonSuaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnButtonSuaNVLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(26, 26, 26))
        );
        pnButtonSuaNVLayout.setVerticalGroup(
            pnButtonSuaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnButtonSuaNVLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        pnButtonThemNV.setBackground(new java.awt.Color(0, 66, 67));
        pnButtonThemNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnButtonThemNVMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnButtonThemNVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnButtonThemNVMouseExited(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_add_user_group_man_man_18px.png"))); // NOI18N
        jLabel16.setText("Thêm");

        javax.swing.GroupLayout pnButtonThemNVLayout = new javax.swing.GroupLayout(pnButtonThemNV);
        pnButtonThemNV.setLayout(pnButtonThemNVLayout);
        pnButtonThemNVLayout.setHorizontalGroup(
            pnButtonThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButtonThemNVLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel16)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnButtonThemNVLayout.setVerticalGroup(
            pnButtonThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButtonThemNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnButtonXoaNV.setBackground(new java.awt.Color(153, 153, 153));
        pnButtonXoaNV.setEnabled(false);
        pnButtonXoaNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnButtonXoaNVMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnButtonXoaNVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnButtonXoaNVMouseExited(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_user_male_18px.png"))); // NOI18N
        jLabel18.setText("Xoá");

        javax.swing.GroupLayout pnButtonXoaNVLayout = new javax.swing.GroupLayout(pnButtonXoaNV);
        pnButtonXoaNV.setLayout(pnButtonXoaNVLayout);
        pnButtonXoaNVLayout.setHorizontalGroup(
            pnButtonXoaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButtonXoaNVLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnButtonXoaNVLayout.setVerticalGroup(
            pnButtonXoaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButtonXoaNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnButtonThemNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnButtonSuaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnButtonXoaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnButtonThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnButtonSuaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnButtonXoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pnThemNhanvien.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(76, 100, 142));
        jLabel2.setText("THÔNG TIN CHI TIẾT NHÂN VIÊN");

        jLabel3.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel3.setText("Mã NV");

        jLabel4.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel4.setText("Tên NV");

        jLabel5.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel5.setText("Giới tính");

        jLabel6.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel6.setText("Địa chỉ");

        jLabel7.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel7.setText("Số điện thoại");

        jLabel8.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel8.setText("Chức vụ");

        txtMaNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMaNV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtMaNV.setEnabled(false);

        txtTenNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTenNV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));

        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDiaChi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));

        bgGioiTinh.add(btnNam);
        btnNam.setText("Nam");
        btnNam.setOpaque(false);
        btnNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNamActionPerformed(evt);
            }
        });

        bgGioiTinh.add(btnNu);
        btnNu.setText("Nữ");
        btnNu.setOpaque(false);
        btnNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(194, 226, 221));

        pnButtonLuuNV.setBackground(new java.awt.Color(0, 66, 67));
        pnButtonLuuNV.setPreferredSize(new java.awt.Dimension(104, 30));
        pnButtonLuuNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnButtonLuuNVMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnButtonLuuNVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnButtonLuuNVMouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Lưu");

        javax.swing.GroupLayout pnButtonLuuNVLayout = new javax.swing.GroupLayout(pnButtonLuuNV);
        pnButtonLuuNV.setLayout(pnButtonLuuNVLayout);
        pnButtonLuuNVLayout.setHorizontalGroup(
            pnButtonLuuNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButtonLuuNVLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnButtonLuuNVLayout.setVerticalGroup(
            pnButtonLuuNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnButtonTaoTK.setBackground(new java.awt.Color(153, 153, 153));
        pnButtonTaoTK.setForeground(new java.awt.Color(153, 153, 153));
        pnButtonTaoTK.setEnabled(false);
        pnButtonTaoTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnButtonTaoTKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnButtonTaoTKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnButtonTaoTKMouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tạo tài khoản");

        javax.swing.GroupLayout pnButtonTaoTKLayout = new javax.swing.GroupLayout(pnButtonTaoTK);
        pnButtonTaoTK.setLayout(pnButtonTaoTKLayout);
        pnButtonTaoTKLayout.setHorizontalGroup(
            pnButtonTaoTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButtonTaoTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnButtonTaoTKLayout.setVerticalGroup(
            pnButtonTaoTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnButtonTaoTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnButtonLuuNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(pnButtonLuuNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnButtonTaoTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cboChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboChucVuActionPerformed(evt);
            }
        });

        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSDT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnThemNhanvienLayout = new javax.swing.GroupLayout(pnThemNhanvien);
        pnThemNhanvien.setLayout(pnThemNhanvienLayout);
        pnThemNhanvienLayout.setHorizontalGroup(
            pnThemNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemNhanvienLayout.createSequentialGroup()
                .addGroup(pnThemNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThemNhanvienLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnThemNhanvienLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(pnThemNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(pnThemNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnThemNhanvienLayout.createSequentialGroup()
                                .addComponent(btnNam)
                                .addGap(56, 56, 56)
                                .addComponent(btnNu))
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnThemNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTenNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cboChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        pnThemNhanvienLayout.setVerticalGroup(
            pnThemNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemNhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnThemNhanvienLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(pnThemNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThemNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThemNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnNam)
                    .addComponent(btnNu))
                .addGap(18, 18, 18)
                .addGroup(pnThemNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThemNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThemNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cboChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnTaoTaikhoan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(76, 100, 142));
        jLabel9.setText("CHI TIẾT TÀI KHOẢN");

        jLabel10.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel10.setText("Mã NV");

        jLabel11.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel11.setText("Tài Khoản");

        jLabel12.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel12.setText("Mật khẩu");

        txtMaTK_add.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMaTK_add.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtMaTK_add.setEnabled(false);

        txtTaiKhoan_add.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTaiKhoan_add.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));

        txtMatKhau_add.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMatKhau_add.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));

        pnButtonLuuTK.setBackground(new java.awt.Color(0, 66, 67));
        pnButtonLuuTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnButtonLuuTKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnButtonLuuTKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnButtonLuuTKMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Lưu");

        javax.swing.GroupLayout pnButtonLuuTKLayout = new javax.swing.GroupLayout(pnButtonLuuTK);
        pnButtonLuuTK.setLayout(pnButtonLuuTKLayout);
        pnButtonLuuTKLayout.setHorizontalGroup(
            pnButtonLuuTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButtonLuuTKLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel13)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnButtonLuuTKLayout.setVerticalGroup(
            pnButtonLuuTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnTaoTaikhoanLayout = new javax.swing.GroupLayout(pnTaoTaikhoan);
        pnTaoTaikhoan.setLayout(pnTaoTaikhoanLayout);
        pnTaoTaikhoanLayout.setHorizontalGroup(
            pnTaoTaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTaoTaikhoanLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnTaoTaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnTaoTaikhoanLayout.createSequentialGroup()
                        .addGroup(pnTaoTaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(36, 36, 36)
                        .addGroup(pnTaoTaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTaiKhoan_add)
                            .addComponent(txtMaTK_add)
                            .addComponent(txtMatKhau_add, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(pnButtonLuuTK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnTaoTaikhoanLayout.setVerticalGroup(
            pnTaoTaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTaoTaikhoanLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addGap(49, 49, 49)
                .addGroup(pnTaoTaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtMaTK_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnTaoTaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTaiKhoan_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnTaoTaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtMatKhau_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnButtonLuuTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pnThemNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(pnTaoTaikhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnThemNhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnTaoTaikhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Nhân viên", jPanel2);

        tblTaikhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Nhân viên", "Tài khoản", "Mật khẩu"
            }
        ));
        tblTaikhoan.setRowHeight(20);
        tblTaikhoan.setSelectionBackground(new java.awt.Color(2, 128, 62));
        jScrollPane2.setViewportView(tblTaikhoan);

        pnButtonXoaTK.setBackground(new java.awt.Color(204, 0, 0));
        pnButtonXoaTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnButtonXoaTKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnButtonXoaTKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnButtonXoaTKMouseExited(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_user_male_18px.png"))); // NOI18N
        jLabel19.setText("Xoá");

        javax.swing.GroupLayout pnButtonXoaTKLayout = new javax.swing.GroupLayout(pnButtonXoaTK);
        pnButtonXoaTK.setLayout(pnButtonXoaTKLayout);
        pnButtonXoaTKLayout.setHorizontalGroup(
            pnButtonXoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButtonXoaTKLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel19)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnButtonXoaTKLayout.setVerticalGroup(
            pnButtonXoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButtonXoaTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnButtonSuaTK.setBackground(new java.awt.Color(0, 66, 67));
        pnButtonSuaTK.setEnabled(false);
        pnButtonSuaTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnButtonSuaTKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnButtonSuaTKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnButtonSuaTKMouseExited(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_edit_property_18px.png"))); // NOI18N
        jLabel27.setText("Sửa");

        javax.swing.GroupLayout pnButtonSuaTKLayout = new javax.swing.GroupLayout(pnButtonSuaTK);
        pnButtonSuaTK.setLayout(pnButtonSuaTKLayout);
        pnButtonSuaTKLayout.setHorizontalGroup(
            pnButtonSuaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnButtonSuaTKLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(26, 26, 26))
        );
        pnButtonSuaTKLayout.setVerticalGroup(
            pnButtonSuaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnButtonSuaTKLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addContainerGap())
        );

        pncardleft.setLayout(new java.awt.CardLayout());

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/account.png"))); // NOI18N
        pncardleft.add(jLabel21, "empty");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(76, 100, 142));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_user_settings_50px.png"))); // NOI18N
        jLabel20.setText("Sửa thông tin tài khoản");

        jLabel22.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel22.setText("Tài khoản");

        jLabel23.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel23.setText("Mật khẩu");

        txtTenTK_up.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        txtTenTK_up.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));

        txtMatKhau_up.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        txtMatKhau_up.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));

        jLabel24.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel24.setText("Mã NV");

        txtMaTK_up.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtMaTK_up.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtMaTK_up.setEnabled(false);

        pnButtonUpdateTK.setBackground(new java.awt.Color(0, 66, 67));
        pnButtonUpdateTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnButtonUpdateTKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnButtonUpdateTKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnButtonUpdateTKMouseExited(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_save_18px.png"))); // NOI18N
        jLabel25.setText("Lưu");

        javax.swing.GroupLayout pnButtonUpdateTKLayout = new javax.swing.GroupLayout(pnButtonUpdateTK);
        pnButtonUpdateTK.setLayout(pnButtonUpdateTKLayout);
        pnButtonUpdateTKLayout.setHorizontalGroup(
            pnButtonUpdateTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButtonUpdateTKLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel25)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnButtonUpdateTKLayout.setVerticalGroup(
            pnButtonUpdateTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButtonUpdateTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenTK_up)
                            .addComponent(txtMatKhau_up)
                            .addComponent(txtMaTK_up, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(168, 168, 168)
                    .addComponent(pnButtonUpdateTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(168, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(44, 44, 44)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtMaTK_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtTenTK_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatKhau_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addContainerGap(328, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(239, 239, 239)
                    .addComponent(pnButtonUpdateTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(239, Short.MAX_VALUE)))
        );

        pncardleft.add(jPanel6, "account");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(pnButtonSuaTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnButtonXoaTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)))
                .addComponent(pncardleft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnButtonSuaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnButtonXoaTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(pncardleft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tài khoản", jPanel3);

        jPanel1.setBackground(new java.awt.Color(76, 100, 142));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("D A N H   S Á C H   N H Â N   V I Ê N");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed

    }//GEN-LAST:event_txtSDTActionPerformed

    private void pnButtonThemNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonThemNVMouseEntered
        enteredBtn(pnButtonThemNV);
    }//GEN-LAST:event_pnButtonThemNVMouseEntered

    private void pnButtonThemNVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonThemNVMouseExited
        exitedBtn(pnButtonThemNV);
    }//GEN-LAST:event_pnButtonThemNVMouseExited

    private void pnButtonSuaNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonSuaNVMouseEntered
        if (pnButtonSuaNV.isEnabled() == true) {
            enteredBtn(pnButtonSuaNV);
        }
    }//GEN-LAST:event_pnButtonSuaNVMouseEntered

    private void pnButtonSuaNVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonSuaNVMouseExited
        if (pnButtonSuaNV.isEnabled() == true) {
            exitedBtn(pnButtonSuaNV);
        }
    }//GEN-LAST:event_pnButtonSuaNVMouseExited

    private void pnButtonXoaNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonXoaNVMouseEntered
        if (pnButtonXoaNV.isEnabled()) {
            pnButtonXoaNV.setBackground(new Color(255, 37, 49));
        }
    }//GEN-LAST:event_pnButtonXoaNVMouseEntered

    private void pnButtonXoaNVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonXoaNVMouseExited
        if (pnButtonXoaNV.isEnabled()) {
            pnButtonXoaNV.setBackground(new Color(204, 0, 0));
        }
    }//GEN-LAST:event_pnButtonXoaNVMouseExited

    private void pnButtonLuuNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonLuuNVMouseEntered
        enteredBtn(pnButtonLuuNV);
    }//GEN-LAST:event_pnButtonLuuNVMouseEntered

    private void pnButtonLuuNVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonLuuNVMouseExited
        exitedBtn(pnButtonLuuNV);
    }//GEN-LAST:event_pnButtonLuuNVMouseExited

    private void pnButtonTaoTKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonTaoTKMouseEntered
        if (pnButtonTaoTK.isEnabled()) {
            enteredBtn(pnButtonTaoTK);
        }
    }//GEN-LAST:event_pnButtonTaoTKMouseEntered

    private void pnButtonTaoTKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonTaoTKMouseExited
        if (pnButtonTaoTK.isEnabled()) {
            exitedBtn(pnButtonTaoTK);
        }
    }//GEN-LAST:event_pnButtonTaoTKMouseExited

    private void pnButtonLuuTKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonLuuTKMouseEntered
        enteredBtn(pnButtonLuuTK);
    }//GEN-LAST:event_pnButtonLuuTKMouseEntered

    private void pnButtonLuuTKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonLuuTKMouseExited
        exitedBtn(pnButtonLuuTK);
    }//GEN-LAST:event_pnButtonLuuTKMouseExited

    private void pnButtonXoaTKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonXoaTKMouseEntered
        pnButtonXoaTK.setBackground(new Color(255, 37, 49));
    }//GEN-LAST:event_pnButtonXoaTKMouseEntered

    private void pnButtonXoaTKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonXoaTKMouseExited
        pnButtonXoaTK.setBackground(new Color(204, 0, 0));
    }//GEN-LAST:event_pnButtonXoaTKMouseExited

    private void pnButtonThemNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonThemNVMouseClicked
        pnButtonTaoTK.setVisible(false);
        pnTaoTaikhoan.setVisible(false);
        if (pnThemNhanvien.isVisible()) {
            if (checkUpdate) {
                txtMaNV.setText("");
                bgGioiTinh.clearSelection();
                txtTenNV.setText("");
                txtSDT.setText("");
                txtDiaChi.setText("");
                cboChucVu.setSelectedIndex(-1);
                chucvuSelected = null;
                checkUpdate = false;
                return;
            } else {
                pnThemNhanvien.setVisible(false);
                pnTaoTaikhoan.setVisible(false);
            }
        } else {
            pnThemNhanvien.setVisible(true);
        }
        txtMaNV.setText("");
        bgGioiTinh.clearSelection();
        txtTenNV.setText("");
        txtSDT.setText("");
        txtDiaChi.setText("");
        cboChucVu.setSelectedIndex(-1);
        chucvuSelected = null;
        checkUpdate = false;
    }//GEN-LAST:event_pnButtonThemNVMouseClicked

    private void pnButtonSuaNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonSuaNVMouseClicked
        pnButtonTaoTK.setVisible(true);
        pnTaoTaikhoan.setVisible(false);
        if (pnButtonSuaNV.isEnabled()) {
            pnThemNhanvien.setVisible(true);
        }
        int rowSelected = tblNhanVien.getSelectedRow();
        if (rowSelected == -1) {
            return;
        }
        String ma = tblNhanVien.getValueAt(rowSelected, 0) + "";
        String ten = tblNhanVien.getValueAt(rowSelected, 1) + "";
        String gioitinh = tblNhanVien.getValueAt(rowSelected, 2) + "";
        String diachi = tblNhanVien.getValueAt(rowSelected, 3) + "";
        String sdt = tblNhanVien.getValueAt(rowSelected, 4) + "";
        String chucvu = tblNhanVien.getValueAt(rowSelected, 5) + "";

        txtMaNV.setText(ma);
        txtTenNV.setText(ten);
        txtDiaChi.setText(diachi);
        txtSDT.setText(sdt);
        gioitinh = gioitinh.trim();
        if (gioitinh.toLowerCase().equals("nam")) {
            btnNam.setSelected(true);
        } else {
            btnNu.setSelected(true);
        }
        for (int i = 0; i < cboChucVu.getItemCount(); i++) {
            if (chucvu.trim().equals(cboChucVu.getItemAt(i) + "")) {
                cboChucVu.setSelectedIndex(i);
                break;
            }
        }
        checkUpdate = true;
        
    }//GEN-LAST:event_pnButtonSuaNVMouseClicked

    private void pnButtonXoaNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonXoaNVMouseClicked
        xuLyXoaNV();
    }//GEN-LAST:event_pnButtonXoaNVMouseClicked

    private void pnButtonLuuNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonLuuNVMouseClicked
        if (checkUpdate) {
            xuLySuaNV();
        } else {
            xuLyLuuNV();
        }
        pnButtonSuaNV.setEnabled(false);
        pnButtonXoaNV.setEnabled(false);
        pnButtonSuaNV.setBackground(colorEnable);
        pnButtonXoaNV.setBackground(colorEnable);
    }//GEN-LAST:event_pnButtonLuuNVMouseClicked

    private void pnButtonTaoTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonTaoTKMouseClicked
        if (pnButtonTaoTK.isEnabled()) {
            if (pnTaoTaikhoan.isVisible()) {
                pnTaoTaikhoan.setVisible(false);
                txtTaiKhoan_add.setText("");
                txtMatKhau_add.setText("");
            } else {
                pnTaoTaikhoan.setVisible(true);
                txtMaTK_add.setText(txtMaNV.getText());
            }
            if (!nvBUS.checkChucVuTheoMaNV(txtMaNV.getText().trim())){
                pnTaoTaikhoan.setVisible(false);
            }
            if (tkBUS.checkTaiKhoan(txtMaNV.getText())) {
                pnTaoTaikhoan.setVisible(false);
            }
        }
    }//GEN-LAST:event_pnButtonTaoTKMouseClicked

    private void pnButtonLuuTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonLuuTKMouseClicked
        if(tkBUS.checkTaiKhoanDaXoa(txtMaTK_add.getText())){
            xulyKhoiPhucTK();
        }
        else{
            xulyThemTK();
        }
    }//GEN-LAST:event_pnButtonLuuTKMouseClicked

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        int rowselected = tblNhanVien.getSelectedRow();
        if (rowselected == -1) {
            return;
        }
       
        pnButtonSuaNV.setEnabled(true);
        pnButtonXoaNV.setEnabled(true);
        xulyEnabledBtn();
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void pnButtonUpdateTKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonUpdateTKMouseEntered
        enteredBtn(pnButtonUpdateTK);
    }//GEN-LAST:event_pnButtonUpdateTKMouseEntered

    private void pnButtonUpdateTKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonUpdateTKMouseExited
        exitedBtn(pnButtonUpdateTK);
    }//GEN-LAST:event_pnButtonUpdateTKMouseExited

    private void pnButtonSuaTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonSuaTKMouseClicked
        CardLayout cardlayout = (CardLayout) pncardleft.getLayout();

        int rowselected = tblTaikhoan.getSelectedRow();
        if (rowselected == -1) {
            return;
        }
        String ma = tblTaikhoan.getValueAt(rowselected, 0) + "";
        String tendn = tblTaikhoan.getValueAt(rowselected, 1) + "";
        String matkhau = tblTaikhoan.getValueAt(rowselected, 2) + "";

        txtMaTK_up.setText(ma);
        txtTenTK_up.setText(tendn);
        txtMatKhau_up.setText(matkhau);

        cardlayout.show(pncardleft, "account");

    }//GEN-LAST:event_pnButtonSuaTKMouseClicked

    private void pnButtonSuaTKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonSuaTKMouseEntered
        enteredBtn(pnButtonSuaTK);
    }//GEN-LAST:event_pnButtonSuaTKMouseEntered

    private void pnButtonSuaTKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonSuaTKMouseExited
        exitedBtn(pnButtonSuaTK);
    }//GEN-LAST:event_pnButtonSuaTKMouseExited

    private void pnButtonUpdateTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonUpdateTKMouseClicked
        xulySuaTK();
        CardLayout cardlayout = (CardLayout) pncardleft.getLayout();
        cardlayout.show(pncardleft, "empty");
    }//GEN-LAST:event_pnButtonUpdateTKMouseClicked

    private void cboChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboChucVuActionPerformed
        if (cboChucVu.getSelectedIndex() == -1/* || cboChucVu.getSelectedIndex() == 0*/) {
            /*pnButtonTaoTK.setBackground(colorEnable);*/
            return;
        }
        chucvuSelected = (ChucVu) cboChucVu.getSelectedItem();
            if (chucvuSelected.getMaChucVu() == 1) {
                pnButtonTaoTK.setEnabled(true);
            } else {
                pnButtonTaoTK.setEnabled(false);
            }
        xulyButtonTaoTK();
    }//GEN-LAST:event_cboChucVuActionPerformed

    private void btnNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNamActionPerformed
        gioitinhSelected = true;
    }//GEN-LAST:event_btnNamActionPerformed

    private void btnNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuActionPerformed
        gioitinhSelected = false;
    }//GEN-LAST:event_btnNuActionPerformed

    private void pnButtonXoaTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonXoaTKMouseClicked

        xulyXoaTK();
    }//GEN-LAST:event_pnButtonXoaTKMouseClicked

    private void xulyEnabledBtn() {
        if (pnButtonSuaNV.isEnabled()) {
            pnButtonSuaNV.setBackground(colorButtonDefault);
        } else {
            pnButtonSuaNV.setBackground(colorEnable);
        }
        if (pnButtonXoaNV.isEnabled()) {
            pnButtonXoaNV.setBackground(new Color(204, 0, 0));
        } else {
            pnButtonSuaNV.setBackground(colorEnable);
        }
    }

    private void xulyButtonTaoTK() {
        if (pnButtonTaoTK.isEnabled()) {
            pnButtonTaoTK.setBackground(colorButtonDefault);
        } else {
            pnButtonTaoTK.setBackground(colorEnable);
            pnTaoTaikhoan.setVisible(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgGioiTinh;
    private javax.swing.JRadioButton btnNam;
    private javax.swing.JRadioButton btnNu;
    private javax.swing.JComboBox<ChucVu> cboChucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnButtonLuuNV;
    private javax.swing.JPanel pnButtonLuuTK;
    private javax.swing.JPanel pnButtonSuaNV;
    private javax.swing.JPanel pnButtonSuaTK;
    private javax.swing.JPanel pnButtonTaoTK;
    private javax.swing.JPanel pnButtonThemNV;
    private javax.swing.JPanel pnButtonUpdateTK;
    private javax.swing.JPanel pnButtonXoaNV;
    private javax.swing.JPanel pnButtonXoaTK;
    private javax.swing.JPanel pnTaoTaikhoan;
    private javax.swing.JPanel pnThemNhanvien;
    private javax.swing.JPanel pncardleft;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTable tblTaikhoan;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMaTK_add;
    private javax.swing.JTextField txtMaTK_up;
    private javax.swing.JTextField txtMatKhau_add;
    private javax.swing.JTextField txtMatKhau_up;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTaiKhoan_add;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTenTK_up;
    // End of variables declaration//GEN-END:variables

    private void enteredBtn(JPanel pn) {
        pn.setBackground(colorButtonHover);
    }

    private void exitedBtn(JPanel pn) {
        pn.setBackground(colorButtonDefault);
    }

    private void hienthiNhanvien() {
        dtmNhanvien = new DefaultTableModel();
        dtmNhanvien.addColumn("Mã NV");
        dtmNhanvien.addColumn("Tên NV");
        dtmNhanvien.addColumn("Giới tính");
        dtmNhanvien.addColumn("Địa chỉ");
        dtmNhanvien.addColumn("SĐT");
        dtmNhanvien.addColumn("Chức vụ");
        tblNhanVien.setModel(dtmNhanvien);
        
        tblNhanVien.getColumnModel().getColumn(0).setMaxWidth(100);
        tblNhanVien.getColumnModel().getColumn(1).setMinWidth(100);
        tblNhanVien.getColumnModel().getColumn(2).setMaxWidth(100);
        tblNhanVien.getColumnModel().getColumn(3).setMinWidth(150);
        
        ChucVuBUS cvBUS = new ChucVuBUS();
        dtmNhanvien.setRowCount(0);
        for (NhanVien nv : nvBUS.getListNhanvien()) {
            Vector<Object> vec = new Vector<>();
            vec.add(nv.getMaNhanVien());
            vec.add(nv.getTenNhanVien());
            vec.add(nv.getGioTinh());
            vec.add(nv.getDiaChi());
            vec.add(nv.getSoDienThoai());
            vec.add(cvBUS.getChucVuTheoMa(nv.getMaChucVu()));
            dtmNhanvien.addRow(vec);
        }
    }

    private void hienthiTaiKhoan() {
        dtmTaikhoan = new DefaultTableModel();
        dtmTaikhoan.addColumn("Mã nhân viên");
        dtmTaikhoan.addColumn("Tài khoản");
        dtmTaikhoan.addColumn("Mật khẩu");
        tblTaikhoan.setModel(dtmTaikhoan);
        dtmTaikhoan.setRowCount(0);
        for (TaiKhoan tk : tkBUS.getlistTaiKhoan()) {
            Vector<Object> vec = new Vector<>();
            vec.add(tk.getMaNhanVien());
            vec.add(tk.getTenDangNhap());
            vec.add(tk.getMatKhau());
            dtmTaikhoan.addRow(vec);
        }
    }

    private void hienthiChucvu() {
        ChucVuBUS cvBUS = new ChucVuBUS();
        cboChucVu.addItem(null);
        ArrayList<ChucVu> dschucvu = cvBUS.getlistChucVu();
        for (ChucVu cv : dschucvu) {
            cboChucVu.addItem(cv);
        }
    }

    private void xuLyLuuNV() {
        if (!btnNam.isSelected() && !btnNu.isSelected()) {
            JOptionPane.showMessageDialog(null, "Chọn giới tính !", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String ten = txtTenNV.getText();
        String sdt = txtSDT.getText();
        String diachi = txtDiaChi.getText();
        if (nvBUS.themNhanVien(ten, sdt, diachi, chucvuSelected, gioitinhSelected)) {
            hienthiNhanvien();
            pnThemNhanvien.setVisible(false);
            pnTaoTaikhoan.setVisible(false);
            bgGioiTinh.clearSelection();
            txtTenNV.setText("");
            txtSDT.setText("");
            txtDiaChi.setText("");
            cboChucVu.setSelectedIndex(-1);
            chucvuSelected = null;
        }
    }

    private void xuLySuaNV() {
        String ma = txtMaNV.getText();
        String ten = txtTenNV.getText();
        String sdt = txtSDT.getText();
        String diachi = txtDiaChi.getText();
        if (nvBUS.suaNhanVien(ma, ten, sdt, diachi, chucvuSelected, gioitinhSelected)) {
            hienthiNhanvien();
            pnThemNhanvien.setVisible(false);
            pnTaoTaikhoan.setVisible(false);
            bgGioiTinh.clearSelection();
            txtMaNV.setText("");
            txtTenNV.setText("");
            txtSDT.setText("");
            txtDiaChi.setText("");
            cboChucVu.setSelectedIndex(-1);
            chucvuSelected = null;
        }
    }

    private void xuLyXoaNV() {
        int rowSelected = tblNhanVien.getSelectedRow();
        if (rowSelected == -1) {
            return;
        }
        String ma = tblNhanVien.getValueAt(rowSelected, 0) + "";
        int ret = JOptionPane.showConfirmDialog(null, "Bạn muốn xoá nhân viên này ?", "Thông báo", JOptionPane.YES_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
            if (nvBUS.xoaNhanVien(ma)) {
                hienthiNhanvien();
            }
        }
    }

    private void xulyThemTK() {
        String matk = txtMaTK_add.getText();
        String tendn = txtTaiKhoan_add.getText();
        String matkhau = txtMatKhau_add.getText();
        if(tkBUS.checkTenBiTrung(tendn)){
            return;
        } else {
            if (tkBUS.themTaiKhoan(matk, tendn, matkhau)) {
            hienthiTaiKhoan();
            txtTaiKhoan_add.setText("");
            txtMatKhau_add.setText("");
            pnTaoTaikhoan.setVisible(false);
        }
        }
        
    }
    
    private void xulyKhoiPhucTK(){
        String matk = txtMaTK_add.getText();
        String tendn = txtTaiKhoan_add.getText();
        String matkhau = txtMatKhau_add.getText();
        if(tkBUS.checkTenBiTrung(tendn)){
            return;
        }else{
            if (tkBUS.khoiphucTaiKhoanDaXoa(matk, tendn, matkhau)) {
            hienthiTaiKhoan();
            txtTaiKhoan_add.setText("");
            txtMatKhau_add.setText("");
            pnTaoTaikhoan.setVisible(false);
        }
        }
        
    }

    private void xulySuaTK() {
        String ma = txtMaTK_up.getText();
        String user = txtTenTK_up.getText();
        String pass = txtMatKhau_up.getText();
        if (tkBUS.suaTaiKhoan(ma, user, pass)) {
            CardLayout cardlayout = (CardLayout) pncardleft.getLayout();
            cardlayout.show(pncardleft, "empty");
            hienthiTaiKhoan();
        }
    }

    private void xulyXoaTK() {
        int rowselected = tblTaikhoan.getSelectedRow();
        if (rowselected == -1) {
            return;
        }
        String ma = tblTaikhoan.getValueAt(rowselected, 0) + "";
        int ret = JOptionPane.showConfirmDialog(null, "Bạn muốn xoá nhân viên này ?", "Thông báo", JOptionPane.YES_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
            if (tkBUS.xoaTaiKhoan(ma)) {
                hienthiTaiKhoan();
            }
        }
    }
}
