/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.HoaDonBUS;
import DTO.HoaDon;
import java.awt.Color;
import java.util.Date;
import java.util.Vector;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class ThongKeUI extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeUI
     */
    Color colorButtonHover = new Color(24, 101, 109);
    Color colorButtonDefault = new Color(0, 66, 67);
    DefaultTableModel dtmHoaDon;
    HoaDonBUS hdBUS;
    int soluonghoadon;
    int tongdoanhthu;

    public ThongKeUI() {
        initComponents();
        
        tblThongKe.getTableHeader().setOpaque(false);
        tblThongKe.getTableHeader().setBackground(new Color(205, 39, 49));
        tblThongKe.getTableHeader().setForeground(Color.white);
        pnChonDate.setVisible(false);
        dtmHoaDon = new DefaultTableModel();
        dtmHoaDon.addColumn("Mã hoá đơn");
        dtmHoaDon.addColumn("Mã NV lập hoá đơn");
        dtmHoaDon.addColumn("Tổng tiền");
        dtmHoaDon.addColumn("Ngày lập");
        tblThongKe.setModel(dtmHoaDon);
        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        tblThongKe.getColumnModel().getColumn(0).setCellRenderer(center);
        tblThongKe.getColumnModel().getColumn(1).setCellRenderer(center);
        tblThongKe.getColumnModel().getColumn(2).setCellRenderer(center);
        tblThongKe.getColumnModel().getColumn(3).setCellRenderer(center);
        tblThongKe.getColumnModel().getColumn(0).setMaxWidth(100);
        
//        hienthiHoaDonAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboThongKe = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongKe = new javax.swing.JTable();
        btnXuatExcel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnChiTiet = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnChonDate = new javax.swing.JPanel();
        pnChonNgay = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        dcsChonNgay = new com.toedter.calendar.JDateChooser();
        btnDanhThuNgay = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        pnChonThang = new javax.swing.JPanel();
        mcsChonThangNam = new com.toedter.calendar.JMonthChooser();
        ycsChonThangNam = new com.toedter.calendar.JYearChooser();
        btnDanhThuThang = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnChonNam = new javax.swing.JPanel();
        btnDanhThuNam = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ycsNam = new com.toedter.calendar.JYearChooser();
        jPanel7 = new javax.swing.JPanel();
        lblSoHoaDon = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblTongDoanhThu = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(76, 100, 142));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("T H Ố N G   K Ê");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Hiển thị");

        cboThongKe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Theo ngày", "Theo tháng", "Theo năm" }));
        cboThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboThongKeActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 4, 1, 1, new java.awt.Color(204, 204, 204)));

        tblThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã hoá đơn", "Nhân viên lập hoá đơn", "Tổng tiền", "Ngày lập"
            }
        ));
        tblThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblThongKe.setRowHeight(20);
        tblThongKe.setSelectionBackground(new java.awt.Color(2, 128, 62));
        jScrollPane1.setViewportView(tblThongKe);
        if (tblThongKe.getColumnModel().getColumnCount() > 0) {
            tblThongKe.getColumnModel().getColumn(0).setMaxWidth(100);
        }
        tblThongKe.getAccessibleContext().setAccessibleName("");

        btnXuatExcel.setBackground(new java.awt.Color(0, 66, 67));
        btnXuatExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXuatExcelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXuatExcelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXuatExcelMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_file_excel_18px_1.png"))); // NOI18N
        jLabel4.setText("Xuất thống kê");

        javax.swing.GroupLayout btnXuatExcelLayout = new javax.swing.GroupLayout(btnXuatExcel);
        btnXuatExcel.setLayout(btnXuatExcelLayout);
        btnXuatExcelLayout.setHorizontalGroup(
            btnXuatExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );
        btnXuatExcelLayout.setVerticalGroup(
            btnXuatExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        btnChiTiet.setBackground(new java.awt.Color(0, 66, 67));
        btnChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChiTietMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChiTietMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChiTietMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Chi tiết hoá đơn");

        javax.swing.GroupLayout btnChiTietLayout = new javax.swing.GroupLayout(btnChiTiet);
        btnChiTiet.setLayout(btnChiTietLayout);
        btnChiTietLayout.setHorizontalGroup(
            btnChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        );
        btnChiTietLayout.setVerticalGroup(
            btnChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(btnXuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXuatExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChiTiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 51, Short.MAX_VALUE)))
        );

        pnChonDate.setBackground(new java.awt.Color(255, 255, 255));
        pnChonDate.setLayout(new java.awt.CardLayout());

        pnChonNgay.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 167, 175)), "Thống kê theo ngày", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(76, 100, 142))); // NOI18N
        pnChonNgay.setOpaque(false);

        jLabel11.setText("Chọn ngày");

        dcsChonNgay.setDateFormatString("dd/MM/yyyy");

        btnDanhThuNgay.setBackground(new java.awt.Color(0, 66, 67));
        btnDanhThuNgay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDanhThuNgayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDanhThuNgayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDanhThuNgayMouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Lọc");

        javax.swing.GroupLayout btnDanhThuNgayLayout = new javax.swing.GroupLayout(btnDanhThuNgay);
        btnDanhThuNgay.setLayout(btnDanhThuNgayLayout);
        btnDanhThuNgayLayout.setHorizontalGroup(
            btnDanhThuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDanhThuNgayLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        btnDanhThuNgayLayout.setVerticalGroup(
            btnDanhThuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnChonNgayLayout = new javax.swing.GroupLayout(pnChonNgay);
        pnChonNgay.setLayout(pnChonNgayLayout);
        pnChonNgayLayout.setHorizontalGroup(
            pnChonNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChonNgayLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(dcsChonNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnChonNgayLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDanhThuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        pnChonNgayLayout.setVerticalGroup(
            pnChonNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChonNgayLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnChonNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dcsChonNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDanhThuNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pnChonDate.add(pnChonNgay, "card3");

        pnChonThang.setBackground(new java.awt.Color(255, 255, 255));
        pnChonThang.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 167, 175)), "Danh thu tháng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(76, 100, 142))); // NOI18N
        pnChonThang.setOpaque(false);

        btnDanhThuThang.setBackground(new java.awt.Color(0, 66, 67));
        btnDanhThuThang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDanhThuThangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDanhThuThangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDanhThuThangMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Lọc");

        javax.swing.GroupLayout btnDanhThuThangLayout = new javax.swing.GroupLayout(btnDanhThuThang);
        btnDanhThuThang.setLayout(btnDanhThuThangLayout);
        btnDanhThuThangLayout.setHorizontalGroup(
            btnDanhThuThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDanhThuThangLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        btnDanhThuThangLayout.setVerticalGroup(
            btnDanhThuThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jLabel12.setText("Chọn tháng năm");

        javax.swing.GroupLayout pnChonThangLayout = new javax.swing.GroupLayout(pnChonThang);
        pnChonThang.setLayout(pnChonThangLayout);
        pnChonThangLayout.setHorizontalGroup(
            pnChonThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnChonThangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnChonThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDanhThuThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnChonThangLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(mcsChonThangNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ycsChonThangNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        pnChonThangLayout.setVerticalGroup(
            pnChonThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChonThangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnChonThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ycsChonThangNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mcsChonThangNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(btnDanhThuThang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pnChonDate.add(pnChonThang, "card2");

        pnChonNam.setBackground(new java.awt.Color(255, 255, 255));
        pnChonNam.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 167, 175)), "Thống kê năm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(76, 100, 142))); // NOI18N
        pnChonNam.setOpaque(false);

        btnDanhThuNam.setBackground(new java.awt.Color(0, 66, 67));
        btnDanhThuNam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDanhThuNamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDanhThuNamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDanhThuNamMouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Lọc");

        javax.swing.GroupLayout btnDanhThuNamLayout = new javax.swing.GroupLayout(btnDanhThuNam);
        btnDanhThuNam.setLayout(btnDanhThuNamLayout);
        btnDanhThuNamLayout.setHorizontalGroup(
            btnDanhThuNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDanhThuNamLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        btnDanhThuNamLayout.setVerticalGroup(
            btnDanhThuNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jLabel16.setText("Chọn năm");

        javax.swing.GroupLayout pnChonNamLayout = new javax.swing.GroupLayout(pnChonNam);
        pnChonNam.setLayout(pnChonNamLayout);
        pnChonNamLayout.setHorizontalGroup(
            pnChonNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChonNamLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(ycsNam, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnChonNamLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDanhThuNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        pnChonNamLayout.setVerticalGroup(
            pnChonNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnChonNamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnChonNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ycsNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnDanhThuNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pnChonDate.add(pnChonNam, "card4");

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSoHoaDon.setFont(new java.awt.Font("Calibri", 1, 35)); // NOI18N
        lblSoHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        lblSoHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoHoaDon.setText("10");
        jPanel7.add(lblSoHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 160, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 2.png"))); // NOI18N
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 11, -1, 130));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(76, 100, 142));
        jLabel5.setText("D O A N H   T H U");

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("VNĐ");
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        lblTongDoanhThu.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblTongDoanhThu.setForeground(new java.awt.Color(255, 255, 255));
        lblTongDoanhThu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTongDoanhThu.setText("100000");
        jPanel10.add(lblTongDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 110, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 1.png"))); // NOI18N
        jPanel10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 11, -1, 130));

        jSeparator1.setBackground(new java.awt.Color(76, 100, 142));
        jSeparator1.setForeground(new java.awt.Color(76, 100, 142));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnChonDate, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5)
                                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 15, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addComponent(pnChonDate, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDanhThuNgayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDanhThuNgayMouseEntered
        enteredBtn(btnDanhThuNgay);
    }//GEN-LAST:event_btnDanhThuNgayMouseEntered

    private void btnDanhThuNgayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDanhThuNgayMouseExited
        exitedBtn(btnDanhThuNgay);
    }//GEN-LAST:event_btnDanhThuNgayMouseExited

    private void btnDanhThuThangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDanhThuThangMouseEntered
        enteredBtn(btnDanhThuThang);
    }//GEN-LAST:event_btnDanhThuThangMouseEntered

    private void btnDanhThuThangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDanhThuThangMouseExited
        exitedBtn(btnDanhThuThang);
    }//GEN-LAST:event_btnDanhThuThangMouseExited

    private void btnDanhThuNamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDanhThuNamMouseEntered
        enteredBtn(btnDanhThuNam);
    }//GEN-LAST:event_btnDanhThuNamMouseEntered

    private void btnDanhThuNamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDanhThuNamMouseExited
        exitedBtn(btnDanhThuNam);
    }//GEN-LAST:event_btnDanhThuNamMouseExited

    private void btnChiTietMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChiTietMouseEntered
        enteredBtn(btnChiTiet);
    }//GEN-LAST:event_btnChiTietMouseEntered

    private void btnChiTietMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChiTietMouseExited
        exitedBtn(btnChiTiet);
    }//GEN-LAST:event_btnChiTietMouseExited

    private void btnXuatExcelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatExcelMouseEntered
        enteredBtn(btnXuatExcel);
    }//GEN-LAST:event_btnXuatExcelMouseEntered

    private void btnXuatExcelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatExcelMouseExited
        exitedBtn(btnXuatExcel);
    }//GEN-LAST:event_btnXuatExcelMouseExited

    private void cboThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboThongKeActionPerformed
        if (cboThongKe.getSelectedIndex() == -1) {
            return;
        }
        switch (cboThongKe.getSelectedIndex()) {
            case 0: {
                pnChonDate.setVisible(false);
                hienthiHoaDonAll();
                break;
            }
            case 1: {
                pnChonDate.setVisible(true);
                pnChonNgay.setVisible(true);
                pnChonThang.setVisible(false);
                pnChonNam.setVisible(false);
                dcsChonNgay.setDate(null);
                break;
            }
            case 2: {
                pnChonDate.setVisible(true);
                pnChonNgay.setVisible(false);
                pnChonThang.setVisible(true);
                pnChonNam.setVisible(false);
                break;
            }
            case 3: {
                pnChonDate.setVisible(true);
                pnChonNgay.setVisible(false);
                pnChonThang.setVisible(false);
                pnChonNam.setVisible(true);
                break;
            }
        }
    }//GEN-LAST:event_cboThongKeActionPerformed

    private void btnChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChiTietMouseClicked
       int rowSelected = tblThongKe.getSelectedRow();
        if(rowSelected == -1)return;
        int mahoadon = (int) tblThongKe.getValueAt(rowSelected, 0);
        new ChiTietHoaDonUI(null, true, mahoadon).setVisible(true);
    }//GEN-LAST:event_btnChiTietMouseClicked

    private void btnDanhThuNgayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDanhThuNgayMouseClicked
        locTheoNgay();
    }//GEN-LAST:event_btnDanhThuNgayMouseClicked

    private void btnDanhThuThangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDanhThuThangMouseClicked
        locTheoThang();
    }//GEN-LAST:event_btnDanhThuThangMouseClicked

    private void btnDanhThuNamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDanhThuNamMouseClicked
        locTheoNam();
    }//GEN-LAST:event_btnDanhThuNamMouseClicked

    private void btnXuatExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatExcelMouseClicked
        ExportExcel ex = new ExportExcel();
        ex.xuatExcel(tblThongKe);
    }//GEN-LAST:event_btnXuatExcelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnChiTiet;
    private javax.swing.JPanel btnDanhThuNam;
    private javax.swing.JPanel btnDanhThuNgay;
    private javax.swing.JPanel btnDanhThuThang;
    private javax.swing.JPanel btnXuatExcel;
    private javax.swing.JComboBox<String> cboThongKe;
    private com.toedter.calendar.JDateChooser dcsChonNgay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblSoHoaDon;
    private javax.swing.JLabel lblTongDoanhThu;
    private com.toedter.calendar.JMonthChooser mcsChonThangNam;
    private javax.swing.JPanel pnChonDate;
    private javax.swing.JPanel pnChonNam;
    private javax.swing.JPanel pnChonNgay;
    private javax.swing.JPanel pnChonThang;
    private javax.swing.JTable tblThongKe;
    private com.toedter.calendar.JYearChooser ycsChonThangNam;
    private com.toedter.calendar.JYearChooser ycsNam;
    // End of variables declaration//GEN-END:variables
    private void enteredBtn(JPanel pn) {
        pn.setBackground(colorButtonHover);
    }

    private void exitedBtn(JPanel pn) {
        pn.setBackground(colorButtonDefault);
    }

    public void hienthiHoaDonAll() {
        hdBUS = new HoaDonBUS();
        
        dtmHoaDon.setRowCount(0);
        soluonghoadon =0;
        tongdoanhthu = 0;
        for (HoaDon hd : hdBUS.getlistHoaDon()) {
            soluonghoadon +=1;
            tongdoanhthu += hd.getTongTien();
            
            Vector<Object> vec = new Vector<>();
            vec.add(hd.getMaHoaDon());
            vec.add(hd.getMaNvQuay());
            vec.add(hdBUS.formatSo(hd.getTongTien()));
            vec.add(hdBUS.formatNgay(hd.getNgayLap()));
            dtmHoaDon.addRow(vec);
        }
        lblSoHoaDon.setText(soluonghoadon+"");
        lblTongDoanhThu.setText(hdBUS.formatSo(tongdoanhthu));
    }
    
    private void locTheoNgay(){
        if(dcsChonNgay.getDate() == null) return;
        hdBUS = new HoaDonBUS();
        Date date = dcsChonNgay.getDate();
        
        dtmHoaDon.setRowCount(0);
        soluonghoadon =0;
        tongdoanhthu = 0;
        for(HoaDon hd :hdBUS.locTheoDate(date)){
            soluonghoadon +=1;
            tongdoanhthu += hd.getTongTien();
            
            Vector<Object> vec = new Vector<>();
            vec.add(hd.getMaHoaDon());
            vec.add(hd.getMaNvQuay());
            vec.add(hdBUS.formatSo(hd.getTongTien()));
            vec.add(hdBUS.formatNgay(hd.getNgayLap()));
            dtmHoaDon.addRow(vec);
        }
        lblSoHoaDon.setText(soluonghoadon+"");
        lblTongDoanhThu.setText(hdBUS.formatSo(tongdoanhthu));
    }
    
    private void locTheoThang(){
        hdBUS = new HoaDonBUS();
        
        int m = mcsChonThangNam.getMonth();
        int y = ycsChonThangNam.getYear();
        dtmHoaDon.setRowCount(0);
        soluonghoadon =0;
        tongdoanhthu = 0;
        for(HoaDon hd :hdBUS.locTheoThangNam(m, y)){
            soluonghoadon +=1;
            tongdoanhthu += hd.getTongTien();
            
            Vector<Object> vec = new Vector<>();
            vec.add(hd.getMaHoaDon());
            vec.add(hd.getMaNvQuay());
            vec.add(hdBUS.formatSo(hd.getTongTien()));
            vec.add(hdBUS.formatNgay(hd.getNgayLap()));
            dtmHoaDon.addRow(vec);
        }
        lblSoHoaDon.setText(soluonghoadon+"");
        lblTongDoanhThu.setText(hdBUS.formatSo(tongdoanhthu));
    }
    
    private void locTheoNam(){
        hdBUS = new HoaDonBUS();
        
        int y = ycsNam.getYear();
        dtmHoaDon.setRowCount(0);
        soluonghoadon =0;
        tongdoanhthu = 0;
        for(HoaDon hd :hdBUS.locTheoNam(y)){
            soluonghoadon +=1;
            tongdoanhthu += hd.getTongTien();
            
            Vector<Object> vec = new Vector<>();
            vec.add(hd.getMaHoaDon());
            vec.add(hd.getMaNvQuay());
            vec.add(hdBUS.formatSo(hd.getTongTien()));
            vec.add(hdBUS.formatNgay(hd.getNgayLap()));
            dtmHoaDon.addRow(vec);
        }
        lblSoHoaDon.setText(soluonghoadon+"");
        lblTongDoanhThu.setText(hdBUS.formatSo(tongdoanhthu));
    }
}
