/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.DangNhapBUS;
import BUS.NhanVienBUS;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class TiemPhoUI extends javax.swing.JFrame {

    /**
     * Creates new form TiemPhoUI
     */
    Color colorDefault = new Color(0,66,67);
    Color colorHover = new Color(24,101,109);
    Color colorFocus = new Color(162,215,227);
    private CardLayout homecard =new CardLayout();
    ThongKeUI thongke = new ThongKeUI();
    
    public TiemPhoUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        QuanLyTiemPhoUI qltp = new QuanLyTiemPhoUI();
        QuanLyNhanVienUI qlnv = new QuanLyNhanVienUI();
        
        pnMenuDatban.setBackground(colorFocus);
        pnhome.setLayout(homecard);
        pnhome.add(qltp,"1");
        pnhome.add(qlnv,"2");
        pnhome.add(thongke,"3");
        pnhome.validate();
        phanQuyen();
        changeUsername();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnhome = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNameLogin = new javax.swing.JLabel();
        pnMenuDatban = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnMenuThongke = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnMenuNhanvien = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnMenuExit = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_25px_2.png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_subtract_25px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(797, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblExit)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblExit)
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnhome.setBackground(new java.awt.Color(255, 255, 255));
        pnhome.setLayout(new javax.swing.BoxLayout(pnhome, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setBackground(new java.awt.Color(0, 66, 67));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/admin.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("QUAN LY TIEM PHO");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        lblNameLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNameLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblNameLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameLogin.setText("ADMIN");

        pnMenuDatban.setBackground(new java.awt.Color(162, 215, 227));
        pnMenuDatban.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnMenuDatbanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnMenuDatbanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnMenuDatbanMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_edit_column_25px.png"))); // NOI18N
        jLabel5.setText("Quản lý đặt bàn");
        jLabel5.setIconTextGap(15);

        javax.swing.GroupLayout pnMenuDatbanLayout = new javax.swing.GroupLayout(pnMenuDatban);
        pnMenuDatban.setLayout(pnMenuDatbanLayout);
        pnMenuDatbanLayout.setHorizontalGroup(
            pnMenuDatbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuDatbanLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnMenuDatbanLayout.setVerticalGroup(
            pnMenuDatbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuDatbanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnMenuThongke.setBackground(new java.awt.Color(0, 66, 67));
        pnMenuThongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnMenuThongkeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnMenuThongkeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnMenuThongkeMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_graph_25px.png"))); // NOI18N
        jLabel9.setText("Thống kê");
        jLabel9.setIconTextGap(15);

        javax.swing.GroupLayout pnMenuThongkeLayout = new javax.swing.GroupLayout(pnMenuThongke);
        pnMenuThongke.setLayout(pnMenuThongkeLayout);
        pnMenuThongkeLayout.setHorizontalGroup(
            pnMenuThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuThongkeLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnMenuThongkeLayout.setVerticalGroup(
            pnMenuThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuThongkeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnMenuNhanvien.setBackground(new java.awt.Color(0, 66, 67));
        pnMenuNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnMenuNhanvienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnMenuNhanvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnMenuNhanvienMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_staff_25px.png"))); // NOI18N
        jLabel7.setText("Quản lý nhân viên");
        jLabel7.setIconTextGap(15);

        javax.swing.GroupLayout pnMenuNhanvienLayout = new javax.swing.GroupLayout(pnMenuNhanvien);
        pnMenuNhanvien.setLayout(pnMenuNhanvienLayout);
        pnMenuNhanvienLayout.setHorizontalGroup(
            pnMenuNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuNhanvienLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnMenuNhanvienLayout.setVerticalGroup(
            pnMenuNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuNhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnMenuExit.setBackground(new java.awt.Color(0, 66, 67));
        pnMenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnMenuExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnMenuExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnMenuExitMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_25px.png"))); // NOI18N
        jLabel6.setText("Đăng xuất");
        jLabel6.setIconTextGap(15);

        javax.swing.GroupLayout pnMenuExitLayout = new javax.swing.GroupLayout(pnMenuExit);
        pnMenuExit.setLayout(pnMenuExitLayout);
        pnMenuExitLayout.setHorizontalGroup(
            pnMenuExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuExitLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnMenuExitLayout.setVerticalGroup(
            pnMenuExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMenuDatban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnMenuExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnMenuNhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnMenuThongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNameLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNameLogin)
                .addGap(37, 37, 37)
                .addComponent(pnMenuDatban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnMenuNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnMenuThongke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnMenuExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnMenuDatbanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMenuDatbanMouseClicked
        pnMenuDatban.setBackground(colorFocus);
        pnMenuThongke.setBackground(colorDefault);
        pnMenuNhanvien.setBackground(colorDefault);
        pnMenuExit.setBackground(colorDefault);
        homecard.show(pnhome, "1");
    }//GEN-LAST:event_pnMenuDatbanMouseClicked

    private void pnMenuDatbanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMenuDatbanMouseEntered
        if(pnMenuDatban.getBackground() != colorFocus){
            pnMenuDatban.setBackground(colorHover);
        }
    }//GEN-LAST:event_pnMenuDatbanMouseEntered

    private void pnMenuDatbanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMenuDatbanMouseExited
        if(pnMenuDatban.getBackground() == colorHover){
            pnMenuDatban.setBackground(colorDefault);
        }
    }//GEN-LAST:event_pnMenuDatbanMouseExited

    private void pnMenuThongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMenuThongkeMouseClicked
        pnMenuDatban.setBackground(colorDefault);
        pnMenuThongke.setBackground(colorFocus);
        pnMenuNhanvien.setBackground(colorDefault);
        pnMenuExit.setBackground(colorDefault);
        homecard.show(pnhome, "3");
        thongke.hienthiHoaDonAll();
    }//GEN-LAST:event_pnMenuThongkeMouseClicked

    private void pnMenuThongkeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMenuThongkeMouseEntered
        if(pnMenuThongke.getBackground() != colorFocus){
            pnMenuThongke.setBackground(colorHover);
        }
    }//GEN-LAST:event_pnMenuThongkeMouseEntered

    private void pnMenuThongkeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMenuThongkeMouseExited
        if(pnMenuThongke.getBackground() == colorHover){
            pnMenuThongke.setBackground(colorDefault);
        }
    }//GEN-LAST:event_pnMenuThongkeMouseExited

    private void pnMenuNhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMenuNhanvienMouseClicked
        pnMenuDatban.setBackground(colorDefault);
        pnMenuThongke.setBackground(colorDefault);
        pnMenuNhanvien.setBackground(colorFocus);
        pnMenuExit.setBackground(colorDefault);
        homecard.show(pnhome, "2");
    }//GEN-LAST:event_pnMenuNhanvienMouseClicked

    private void pnMenuNhanvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMenuNhanvienMouseEntered
        if(pnMenuNhanvien.getBackground() != colorFocus){
            pnMenuNhanvien.setBackground(colorHover);
        }
    }//GEN-LAST:event_pnMenuNhanvienMouseEntered

    private void pnMenuNhanvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMenuNhanvienMouseExited
        if(pnMenuNhanvien.getBackground() == colorHover){
            pnMenuNhanvien.setBackground(colorDefault);
        }
    }//GEN-LAST:event_pnMenuNhanvienMouseExited

    private void pnMenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMenuExitMouseClicked
        int ret = JOptionPane.showConfirmDialog(null, "Bạn muốn đăng xuất ?", "Thoát", JOptionPane.YES_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
            this.dispose();
            LoginForm lg = new LoginForm();
            lg.setVisible(true);
        }
    }//GEN-LAST:event_pnMenuExitMouseClicked

    private void pnMenuExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMenuExitMouseEntered
        if(pnMenuExit.getBackground() != colorFocus){
            pnMenuExit.setBackground(colorHover);
        }
    }//GEN-LAST:event_pnMenuExitMouseEntered

    private void pnMenuExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMenuExitMouseExited
        if(pnMenuExit.getBackground() == colorHover){
            pnMenuExit.setBackground(colorDefault);
        }
    }//GEN-LAST:event_pnMenuExitMouseExited

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
       System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
//    gui.MenuLeft mnu = new gui.MenuLeft();
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblNameLogin;
    private javax.swing.JPanel pnMenuDatban;
    private javax.swing.JPanel pnMenuExit;
    private javax.swing.JPanel pnMenuNhanvien;
    private javax.swing.JPanel pnMenuThongke;
    private javax.swing.JPanel pnhome;
    // End of variables declaration//GEN-END:variables

    private void phanQuyen() {
        if(DangNhapBUS.taikhoanlogin.getQuyen() != 0){
            pnMenuNhanvien.setVisible(false);
            pnMenuThongke.setVisible(false);
        }
    }

    private void changeUsername() {
        NhanVienBUS nvBUS = new NhanVienBUS();
        int ma = DangNhapBUS.taikhoanlogin.getMaNhanVien();
        String name = nvBUS.getTenTheoma(ma);
        
        lblNameLogin.setText(name.toUpperCase());
    }
}
